### ISSUE TITLE
can not use in mac os

### ISSUE THREAD

**Issue by greatlim** [eternal-flame-AD/evol_autowalk#2]
- 分辨率已经改成和作者测试型号一样，测试用的是Mumu模拟器，adb应该正常
- 报错：AttributeError: module 'subprocess' has no attribute 'STARTUPINFO'
- 我想可能是因为mac os不能支持subprocess.STARTUPINFO，不知道作者可以不可以在mac上测试一下

**Comment by eternal-flame-AD** [comment]
https://github.com/eternal-flame-AD/evol_autowalk/pull/3
I have submitted a pull request on the repository and please feel free to test the preview :)
Further reports are highly appreciated. Thanks.

**Comment by greatlim** [comment]
Now, it can run in mac os perfectly. Thanks a lot~

**Comment by eternal-flame-AD** [comment]
I will set up my testing environment these days and optimize macOS performance thereafter. Thanks for the report:)

**Comment by eternal-flame-AD** [comment]
I have replaced os.system with subprocess.Popen (withtout the startup info parameter) and I'm wondering whether it would work better on MacOS. If you experience any problem please tell me thanks.

**Comment by greatlim** [comment]
It doesn't work. You may forget to import subprocess in this version. 
However, after importing this module, it still can not work.
Hope this can help you to solve this issue.

```
Traceback (most recent call last):
  File "evol_auto_macos.py", line 207, in <module>
    main()
  File "evol_auto_macos.py", line 197, in main
    tap(956,1870)
  File "evol_auto_macos.py", line 108, in tap
    subprocess.Popen(cmd)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'adb shell input tap 956 1870': 'adb shell input tap 956 1870'

**Comment by eternal-flame-AD** [comment]
I reverted the commit and created a new branch to deal with the problem. I think the problem may be caused by that not like os.system, subprocess doesn't read the PATH variable so it can't find the adb executable.
In the new branch I added the shell=True parameter but according to my knowledge this may cause performance issues.
I apologize that I am really unfamiliar with MacOS and I had great difficulty debugging on MacOS. Which one works better on your MacOS, the subprocess(shell=True) implementation or the traditional os.system implementaion?

**Comment by greatlim** [comment]
It seems better and faster than the first version that use os.system. 
Thank you for your work. 
Maybe, it's the key to solve this problem.

**Comment by eternal-flame-AD** [comment]
Thanks for your report:)
I will merge this branch later.

**Comment by eternal-flame-AD** [comment]
If you encounter further problems or wish new improvements feel free to open another issue and I'll be there asap :)
