### ISSUE TITLE
关于新版已经加入了自动剧情

### ISSUE THREAD

**Issue by zhoujobor** [eternal-flame-AD/evol_autowalk#5]
你好，新版已经加入了自动剧情，目前会一直开关自动剧情，请问有什么好的办法让它点一下就好了吗？
我在想用图像的灰度值来匹配，结果不行。

**Comment by eternal-flame-AD** [comment]
我试着支持一下QWQ

**Comment by eternal-flame-AD** [comment]
我这边刚刚做了一些修改，在Bluestacks上测试了1080p和720p两种分辨率30分钟，已经可以正常工作

**Comment by eternal-flame-AD** [comment]
图像的匹配我这边用的是自己的函数
pixel_match(im,target_x,target_y,target_r,target_g,target_b,diff,debug=False)
取得截图文件后寻找特征点的rgb值容错匹配

**Comment by zhoujobor** [comment]
我今天刚好写完准备传一下的，结果你就更新了2333
我是截图那个按钮区域然后缩放到15*15像素，然后取rgb数值二值化图像拿到二值数列，然后去判断图像相似度是不是属于自动中。自动中就不执行Determine_status(im)函数，算是取巧了吧蛤蛤蛤

**Comment by eternal-flame-AD** [comment]
主要是感觉自动中还是有点慢啦QWQ所以干脆发现在剧情中就狂点跳过咯

**Comment by eternal-flame-AD** [comment]
Please open a new issue if you encounter any other problem.  Thanks.

**Comment by eternal-flame-AD** [comment]
Please open a new issue if you encounter any other problem.  Thanks.
